const Title = function(title){
    let text = title || {};
    this.aa = text.aa; //Afar
    this.ab = text.ab; //Abkhazian
    this.af = text.af; //Afrikaans
    this.ak = text.ak; //Akan
    this.sq = text.sq; //Albanian
    this.am = text.am; //Amharic
    this.ar = text.ar; //Arabic
    this.an = text.an; //Aragonese
    this.hy = text.hy; //Armenian
    this.as = text.as; //Assamese
    this.av = text.av; //Avaric
    this.ae = text.ae; //Avestan
    this.ay = text.ay; //Aymara
    this.az = text.az;//Azerbaijani
    this.ba = text.ba; //Bashkir
    this.bm = text.bm; //Bambara
    this.eu = text.eu; //Basque
    this.be = text.be; //Belarusian
    this.bn = text.bn; //Bengali
    this.bi = text.bi; //Bislama
    this.bo = text.bo; //Tibetan
    this.bs = text.bs; //Bosnian
    this.br = text.br; //Breton
    this.bg = text.bg; //Bulgarian
    this.me = text.me; //Burmese
    this.ca = text.ca; //Catalan; Valencian
    this.cak = text.cak; //Maya Kaqchikel
    this.cs = text.cs; //Czech
    this.ch = text.ch; //Chamorro
    this.ce = text.ce; //Chechen
    this.zh = text.zh; //Chinese
    this.cv = text.cv; //Chuvash
    this.kw = text.kw; //Cornish
    this.co = text.co; //Corsican
    this.cr = text.cr; //Cree
    this.cy = text.cy; //Welsh
    this.da = text.da; //Danish
    this.de = text.de; //German
    this.dv = text.dv; //Divehi; Dhivehi; Maldivian
    this.nl = text.nl; //Dutch; Flemish
    this.dz = text.dz; //Dzongkha
    this.el = text.el; //Greek
    this.en = text.en; //English
    this.enca = text.enCa; //English (Canadian)
    this.enus = text.enUs; //English (US)
    this.eo = text.eo; //Esperanto
    this.et = text.et; //Estonian
    this.ee = text.ee; //Ewe
    this.fo = text.eo; //Faroese
    this.fa = text.fa; //Persian
    this.fj = text.fj; //Fijian
    this.fi = text.fi; //Finnish
    this.fr = text.fr; //French
    this.fy = text.fy; //Western Frisian
    this.ff = text.ff; //Fulah
    this.ka = text.ka; //Georgian
    this.gd = text.gd; //Gaelic; Scottish Gaelic
    this.ga = text.ga; //Irish
    this.gl = text.gl; //Galician
    this.gv = text.gv; //Manx
    this.gn = text.gn; //Guarani
    this.gu = text.gu; //Gujarati
    this.ht = text.ht; //Haitian; Haitian Creole
    this.ha = text.ha; //Hausa
    this.he = text.he; //Hebrew
    this.hz = text.hz; //Herero
    this.hi = text.hi; //Hindi
    this.ho = text.ho; //Hiri Motu
    this.hr = text.hr; //Croatian
    this.hu = text.hu; //Hungarian
    this.if = text.if; //Igbo
    this.is = text.is; //Icelandic
    this.io = text.io; //Ido
    this.ii = text.ii; //Sichuan Yi; Nuosu
    this.iu = text.iu; //Inuktitut
    this.ie = text.ie; //Interlingue; Occidental
    this.ia = text.ia; //Interlingua (International Auxiliary Language Association)
    this.id = text.id; //Indonesian
    this.ik = text.ik; //Inupiaq
    this.it = text.it; //Italian
    this.jv = text.jv; //Javanese
    this.ja = text.ja; //Japanese
    this.kl = text.kl; //Kalaallisut; Greenlandic
    this.kn = text.kn; //Kannada
    this.ks = text.ks; //Kashmiri
    this.kr = text.kr; //Kanuri
    this.kk = text.kk; //Kazakh
    this.km = text.km; //Central Khmer
    this.ki = text.ki; //Kikuyu; Gikuyu
    this.rw = text.rw; //Kinyarwanda
    this.ky = text.ky; //Kirghiz; Kyrgyz
    this.kv = text.kv; //Komi
    this.kg = text.kg; //Kongo
    this.ko = text.ko; //Korean
    this.kj = text.kj; //Kuanyama; Kwanyama
    this.ku = text.ku; //Kurdish
    this.kab = text.kab; //Taqbaylit
    this.lo = text.lo; //Lao
    this.la = text.la; //Latin
    this.lv = text.lv; //Latvian
    this.li = text.li; //Limburgan; Limburger; Limburgish
    this.ln = text.ln; //Lingala
    this.lt = text.lt; //Lithuanian
    this.lb = text.lb; //Luxembourgish; Letzeburgesch
    this.lu = text.lu; //Luba-Katanga
    this.lg = text.lg; //Ganda
    this.mk = text.mk; //Macedonian
    this.mh = text.mh; //Marshallese
    this.ml = text.ml; //Malayalam
    this.mi = text.mi; //Maori
    this.mr = text.mr; //Marathi
    this.ms = text.ms; //Malay
    this.mg = text.mg; //Malagasy
    this.mt = text.mt; //Maltese
    this.mn = text.mn; //Mongolian
    this.my = text.my; //Burmese
    this.na = text.na; //Nauru
    this.nv = text.nv; //Navajo; Navaho
    this.nr = text.nr; //Ndebele; South; South Ndebele
    this.nd = text.nd; //Ndebele; North; North Ndebele
    this.ng = text.ng; //Ndonga
    this.ne = text.ne; //Nepali
    this.nn = text.nn; //Norwegian Nynorsk; Nynorsk; Norwegian
    this.nb = text.nb; //Bokmål; Norwegian; Norwegian Bokmål
    this.no = text.no; //Norwegian
    this.ny = text.ny; //Chichewa; Chewa; Nyanja
    this.oc = text.oc; //Occitan
    this.oj = text.oj; //Ojibwa
    this.or = text.or; //Oriya
    this.om = text.om; //Oromo
    this.os = text.os; //Ossetian; Ossetic
    this.pa = text.pa; //Panjabi; Punjabi
    this.pi = text.pi; //Pali
    this.pl = text.pl; //Polish
    this.pt = text.pt; //Portuguese
    this.ptbr = text.ptBr; //Portuguese (Brasil)
    this.ps = text.ps; //Pushto; Pashto
    this.qu = text.qu; //Quechua
    this.rm = text.rm; //Romansh
    this.ro = text.ro; //Romanian
    this.romd = text.roMd; //Romanian Moldova
    this.rn = text.rn; //Rundi
    this.ru = text.ru; //Russian
    this.sg = text.sg; //Sango
    this.sa = text.sa; //Sanskrit
    this.si = text.si; //Sinhala; Sinhalese	
    this.sk = text.sk; //Slovak
    this.sl = text.sl; //Slovenian
    this.se = text.se; //Northern Sami
    this.sm = text.sm; //Samoan
    this.sn = text.sn; //Shona
    this.sd = text.sd; //Sindhi
    this.so = text.so; //Somali
    this.st = text.st; //Sotho; Southern
    this.es = text.es; //Spanish; Castilian
    this.esar = text.esAr; //Spanish (Argentina);
    this.escl = text.esCl; //Spanish (Chile)
    this.esmx = text.esMx; //Spanish (Mexico)
    this.sc = text.sc; //Sardinian
    this.sr = text.sr; //Serbian
    this.ss = text.ss; //Swati
    this.su = text.su; //Sundanese
    this.sw = text.sw; //Swahili
    this.sv = text.sv; //Swedish
    this.ty = text.ty; //Tahitian
    this.ta = text.ta; //Tamil
    this.tt = text.tt; //Tatar
    this.te = text.te; //Telugu
    this.tg = text.tg; //Tajik
    this.tl = text.tl; //Tagalog
    this.th = text.th; //Thai
    this.ti = text.ti; //Tigrinya
    this.to = text.to; //Tonga (Tonga Islands)
    this.tn = text.tn; //Tswana
    this.ts = text.ts; //Tsonga
    this.tk = text.tk; //Turkmen
    this.tr = text.tr; //Turkish
    this.tw = text.tw; //Twi
    this.ug = text.ug; //Uighur; Uyghur
    this.uk = text.uk; //Ukrainian
    this.urdu = text.ur; //Urdu
    this.uz = text.uz; //Uzbek
    this.ve = text.ve; //Venda
    this.vi = text.vi; //Vietnamese
    this.vo = text.vo; //Volapük
    this.wa = text.wa; //Walloon
    this.wo = text.wo; //Wolof
    this.xh = text.xh; //Xhosa
    this.yi = text.yi; //Yiddish
    this.yo = text.yo; //Yoruba
    this.za = text.za; //Zhuang; Chuang
    this.zu = text.zu //Zulu
};
export default Title;