export const Languages = {
    "aa": "Afar",
    "ab": "Abkhazian",
    "af": "Afrikaans",
    "ak": "Akan",
    "sq": "Albanian",
    "am": "Amharic",
    "ar": "Arabic",
    "an": "Aragonese",
    "hy": "Armenian",
    "as": "Assamese",
    "av": "Avaric",
    "ae": "Avestan",
    "ay": "Aymara",
    "az": "Azerbaijani",
    "ba": "Bashkir",
    "bm": "Bambara",
    "eu": "Basque",
    "be": "Belarusian",
    "bn": "Bengali",
    "bi": "Bislama",
    "bo": "Tibetan",
    "bs": "Bosnian",
    "br": "Breton",
    "bg": "Bulgarian",
    "me": "Burmese",
    "ca": "Catalan",
    "cak": "Maya Kaqchikel",
    "cs": "Czech",
    "ch": "Chamorro",
    "ce": "Chechen",
    "zh": "Chinese",
    "cv": "Chuvash",
    "kw": "Cornish",
    "co": "Corsican",
    "cr": "Cree",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "dv": "Divehi (Maldivian)",
    "nl": "Dutch (Flemish)",
    "dz": "Dzongkha",
    "el": "Greek",
    "en": "English",
    "enca": "English (Canadian)",
    "enus": "English (US)",
    "eo": "Esperanto",
    "et": "Estonian",
    "ee": "Ewe",
    "fo": "Faroese",
    "fa": "Persian",
    "fj": "Fijian",
    "fi": "Finnish",
    "fr": "French",
    "fy": "Western Frisian",
    "ff": "Fulah",
    "ka": "Georgian",
    "gd": "Gaelic",
    "ga": "Irish",
    "gl": "Galician",
    "gv": "Manx",
    "gn": "Guarani",
    "gu": "Gujarati",
    "ht": "Haitian (Creole)",
    "ha": "Hausa",
    "he": "Hebrew",
    "hz": "Herero",
    "hi": "Hindi",
    "ho": "Hiri Motu",
    "hr": "Croatian",
    "hu": "Hungarian",
    "if": "Igbo",
    "is": "Icelandic",
    "io": "Ido",
    "ii": "Sichuan Yi (Nuosu)",
    "iu": "Inuktitut",
    "ie": "Interlingue (Occidental)",
    "ia": "Interlingua (International Auxiliary Language Association)",
    "id": "Indonesian",
    "ik": "Inupiaq",
    "it": "Italian",
    "jv": "Javanese",
    "ja": "Japanese",
    "kl": "Kalaallisut (Greenlandic)",
    "kn": "Kannada",
    "ks": "Kashmiri",
    "kr": "Kanuri",
    "kk": "Kazakh",
    "km": "Central Khmer",
    "ki": "Kikuyu (Gikuyu)",
    "rw": "Kinyarwanda",
    "ky": "Kyrgyz",
    "kv": "Komi",
    "kg": "Kongo",
    "ko": "Korean",
    "kj": "Kwanyama",
    "ku": "Kurdish",
    "kab": "Taqbaylit",
    "lo": "Lao",
    "la": "Latin",
    "lv": "Latvian",
    "li": "Limburgan",
    "ln": "Lingala",
    "lt": "Lithuanian",
    "lb": "Luxembourgish",
    "lu": "Luba-Katanga",
    "lg": "Ganda",
    "mk": "Macedonian",
    "mh": "Marshallese",
    "ml": "Malayalam",
    "mi": "Maori",
    "mr": "Marathi",
    "ms": "Malay",
    "mg": "Malagasy",
    "mt": "Maltese",
    "mn": "Mongolian",
    "my": "Burmese",
    "na": "Nauru",
    "nv": "Navajo",
    "nr": "South Ndebele",
    "nd": "North Ndebele",
    "ng": "Ndonga",
    "ne": "Nepali",
    "nn": "Norwegian Nynorsk",
    "nb": "Norwegian Bokmål",
    "no": "Norwegian",
    "ny": "Chichewa (Nyanja)",
    "oc": "Occitan",
    "oj": "Ojibwa",
    "or": "Oriya",
    "om": "Oromo",
    "os": "Ossetian",
    "pa": "Panjabi",
    "pi": "Pali",
    "pl": "Polish",
    "pt": "Portuguese",
    "ptbr": "Portuguese (Brasil)",
    "ps": "Pushto",
    "qu": "Quechua",
    "rm": "Romansh",
    "ro": "Romanian",
    "romd": "Romanian (Moldova)",
    "rn": "Rundi",
    "ru": "Russian",
    "sg": "Sango",
    "sa": "Sanskrit",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "se": "Northern Sami",
    "sm": "Samoan",
    "sn": "Shona",
    "sd": "Sindhi",
    "so": "Somali",
    "st": "Sotho, Southern",
    "es": "Spanish",
    "esar": "Spanish (Argentina)",
    "escl": "Spanish (Chile)",
    "esmx": "Spanish (Mexico)",
    "sc": "Sardinian",
    "sr": "Serbian",
    "ss": "Swati",
    "su": "Sundanese",
    "sw": "Swahili",
    "sv": "Swedish",
    "ty": "Tahitian",
    "ta": "Tamil",
    "tt": "Tatar",
    "te": "Telugu",
    "tg": "Tajik",
    "tl": "Tagalog",
    "th": "Thai",
    "ti": "Tigrinya",
    "to": "Tonga (Tonga Islands)",
    "tn": "Tswana",
    "ts": "Tsonga",
    "tk": "Turkmen",
    "tr": "Turkish",
    "tw": "Twi",
    "ug": "Uighur",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "ve": "Venda",
    "vi": "Vietnamese",
    "vo": "Volapük",
    "wa": "Walloon",
    "wo": "Wolof",
    "xh": "Xhosa",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "za": "Zhuang",
    "zu": "Zulu"
}