export const FETCH_ALL_ARTICLES_REQUEST = 'FETCH_ALL_ARTICLES_REQUEST';
export const FETCH_ALL_ARTICLES_SUCCESS = 'FETCH_ALL_ARTICLES_SUCCESS';
export const FETCH_ALL_ARTICLES_FAILURE = 'FETCH_ALL_ARTICLES_FAILURE';

export const UPLOAD_ARTICLE_REQUEST = 'UPLOAD_ARTICLE_REQUEST';
export const UPLOAD_ARTICLE_SUCCESS = 'UPLOAD_ARTICLE_SUCCESS';
export const UPLOAD_ARTICLE_FAILURE= 'UPLOAD_ARTICLE_FAILURE';

export const ADD_UPDATE_ARTICLE_REQUEST = 'ADD_UPDATE_ARTICLE_REQUEST';
export const ADD_UPDATE_ARTICLE_SUCCESS = 'ADD_UPDATE_ARTICLE_SUCCESS';
export const ADD_UPDATE_ARTICLE_FAILURE= 'ADD_UPDATE_ARTICLE_FAILURE';

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';

export const FETCH_DELETED_ARTICLES_REQUEST = 'FETCH_DELETED_ARTICLES_REQUEST';
export const FETCH_DELETED_ARTICLES_SUCCESS = 'FETCH_DELETED_ARTICLES_SUCCESS';
export const FETCH_DELETED_ARTICLES_FAILURE = 'FETCH_DELETED_ARTICLES_FAILURE';

export const PERMANENT_DELETE_ARTICLE_REQUEST = 'PERMANENT_DELETE_ARTICLE_REQUEST';
export const PERMANENT_DELETE_ARTICLE_SUCCESS = 'PERMANENT_DELETE_ARTICLE_SUCCESS';
export const PERMANENT_DELETE_ARTICLE_FAILURE = 'PERMANENT_DELETE_ARTICLE_FAILURE';

export const RECOVER_ARTICLE_REQUEST = 'RECOVER_ARTICLE_REQUEST';
export const RECOVER_ARTICLE_SUCCESS = 'RECOVER_ARTICLE_SUCCESS';
export const RECOVER_ARTICLE_FAILURE = 'RECOVER_ARTICLE_FAILURE';

export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';

export const FETCH_ARTICLE_CONTENT_REQUEST = 'FETCH_ARTICLE_CONTENT_REQUEST';
export const FETCH_ARTICLE_CONTENT_SUCCESS = 'FETCH_ARTICLE_CONTENT_SUCCESS';
export const FETCH_ARTICLE_CONTENT_FAILURE = 'FETCH_ARTICLE_CONTENT_FAILURE';

export const SELECT_ARTICLE = 'SELECT_ARTICLE';

export const SET_ARTICLE_PUBLISH_REQUEST = 'SET_ARTICLE_PUBLISH_REQUEST';
export const SET_ARTICLE_PUBLISH_SUCCESS = 'SET_ARTICLE_PUBLISH_SUCCESS';
export const SET_ARTICLE_PUBLISH_FAILURE = 'SET_ARTICLE_PUBLISH_FAILURE';

export const FETCH_ARTICLE_BACKUP_REQUEST = 'FETCH_ARTICLE_BACKUP_REQUEST';
export const FETCH_ARTICLE_BACKUP_SUCCESS = 'FETCH_ARTICLE_BACKUP_SUCCESS';
export const FETCH_ARTICLE_BACKUP_FAILURE = 'FETCH_ARTICLE_BACKUP_FAILURE';

export const FETCH_ARTICLE_BACKUP_CONTENT_REQUEST = 'FETCH_ARTICLE_BACKUP_CONTENT_REQUEST';
export const FETCH_ARTICLE_BACKUP_CONTENT_SUCCESS = 'FETCH_ARTICLE_BACKUP_CONTENT_SUCCESS';
export const FETCH_ARTICLE_BACKUP_CONTENT_FAILURE = 'FETCH_ARTICLE_BACKUP_CONTENT_FAILURE';

export const RESTORE_ARTICLE_BACKUP_REQUEST = 'RESTORE_ARTICLE_REQUEST';
export const RESTORE_ARTICLE_BACKUP_SUCCESS = 'RESTORE_ARTICLE_SUCCESS';
export const RESTORE_ARTICLE_BACKUP_FAILURE = 'RESTORE_ARTICLE_FAILURE';

export const STOP_FORCED_UPDATE = 'STOP_ARTICLES_FORCED_UPDATE';