export const FETCH_NEWSLETTERS_REQUEST = 'FETCH_NEWSLETTERS_REQUEST';
export const FETCH_NEWSLETTERS_SUCCESS = 'FETCH_NEWSLETTERS_SUCCESS';
export const FETCH_NEWSLETTERS_FAILURE = 'FETCH_NEWSLETTERS_FAILURE';

export const DELETE_NEWSLETTER_REQUEST = 'DELETE_NEWSLETTER_REQUEST';
export const DELETE_NEWSLETTER_SUCCESS = 'DELETE_NEWSLETTER_SUCCESS';
export const DELETE_NEWSLETTER_FAILURE = 'DELETE_NEWSLETTER_FAILURE';

export const ADD_UPDATE_NEWSLETTER_REQUEST = 'ADD_UPDATE_NEWSLETTER_REQUEST';
export const ADD_UPDATE_NEWSLETTER_SUCCESS = 'ADD_UPDATE_NEWSLETTER_SUCCESS';
export const ADD_UPDATE_NEWSLETTER_FAILURE= 'ADD_UPDATE_NEWSLETTER_FAILURE';

export const FETCH_NEWSLETTER_REQUEST = 'FETCH_NEWSLETTER_REQUEST';
export const FETCH_NEWSLETTER_SUCCESS = 'FETCH_NEWSLETTER_SUCCESS';
export const FETCH_NEWSLETTER_FAILURE = 'FETCH_NEWSLETTER_FAILURE';

export const FETCH_NEWSLETTER_CONTENT_REQUEST = 'FETCH_NEWSLETTER_CONTENT_REQUEST';
export const FETCH_NEWSLETTER_CONTENT_SUCCESS = 'FETCH_NEWSLETTER_CONTENT_SUCCESS';
export const FETCH_NEWSLETTER_CONTENT_FAILURE = 'FETCH_NEWSLETTER_CONTENT_FAILURE';

export const SEND_NEWSLETTER_REQUEST = 'SEND_NEWSLETTER_REQUEST';
export const SEND_NEWSLETTER_SUCCESS = 'SEND_NEWSLETTER_SUCCESS';
export const SEND_NEWSLETTER_FAILURE = 'SEND_NEWSLETTER_FAILURE';

export const FETCH_SUBSCRIBERS_REQUEST = 'FETCH_SUBSCRIBERS_REQUEST';
export const FETCH_SUBSCRIBERS_SUCCESS = 'FETCH_SUBSCRIBERS_SUCCESS';
export const FETCH_SUBSCRIBERS_FAILURE = 'FETCH_SUBSCRIBERS_FAILURE';

export const DELETE_SUBSCRIBER_REQUEST = 'DELETE_SUBSCRIBER_REQUEST';
export const DELETE_SUBSCRIBER_SUCCESS = 'DELETE_SUBSCRIBER_SUCCESS';
export const DELETE_SUBSCRIBER_FAILURE = 'DELETE_SUBSCRIBER_FAILURE';

export const SELECT_NEWSLETTER = 'SELECT_NEWSLETTER';
export const STOP_FORCED_UPDATE = 'STOP_NEWSLETTER_FORCED_UPDATE';


export const FETCH_SUB_TEMPLATE_REQUEST = 'FETCH_SUB_TEMPLATE_REQUEST';
export const FETCH_SUB_TEMPLATE_SUCCESS = 'FETCH_SUB_TEMPLATE_SUCCESS';
export const FETCH_SUB_TEMPLATE_FAILURE = 'FETCH_SUB_TEMPLATE_FAILURE';

export const ADD_UPDATE_SUB_TEMPLATE_REQUEST = 'ADD_UPDATE_SUB_TEMPLATE_REQUEST';
export const ADD_UPDATE_SUB_TEMPLATE_SUCCESS = 'ADD_UPDATE_SUB_TEMPLATE_SUCCESS';
export const ADD_UPDATE_SUB_TEMPLATE_FAILURE = 'ADD_UPDATE_SUB_TEMPLATE_FAILURE';

export const FETCH_SUB_TEMPLATE_CONTENT_REQUEST = 'FETCH_SUB_TEMPLATE_CONTENT_REQUEST';
export const FETCH_SUB_TEMPLATE_CONTENT_SUCCESS = 'FETCH_SUB_TEMPLATE_CONTENT_SUCCESS';
export const FETCH_SUB_TEMPLATE_CONTENT_FAILURE = 'FETCH_SUB_TEMPLATE_CONTENT_FAILURE';