export const FETCH_SETTINGS_REQUEST = 'FETCH_SETTINGS_REQUEST';
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export const FETCH_SETTINGS_FAILURE = 'FETCH_SETTINGS_FAILURE';

export const UPDATE_SETTINGS_REQUEST = 'UPDATE_SETTINGS_REQUEST';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';
export const UPDATE_SETTINGS_FAILURE = 'UPDATE_SETTINGS_FAILURE';

export const LAUNCH_DEPLOYMENT_REQUEST = 'LAUNCH_DEPLOYMENT_REQUEST';
export const LAUNCH_DEPLOYMENT_SUCCESS = 'LAUNCH_DEPLOYMENT_SUCCESS';
export const LAUNCH_DEPLOYMENT_FAILURE = 'LAUNCH_DEPLOYMENT_FAILURE';

export const SET_USER_DATA = 'SET_USER_DATA';
export const READ_STORAGE_DARKMODE = 'READ_STORAGE_DARKMODE';
export const SIGNALR_CONNECTED = 'SIGNALR_CONNECTED';
export const SIGNALR_SEND_MESSAGE_REQUEST =  'SIGNALR_SEND_MESSAGE_REQUEST';
export const SIGNALR_SEND_MESSAGE_SUCCESS =  'SIGNALR_SEND_MESSAGE_SUCCESS';
export const SIGNALR_SEND_MESSAGE_FAILURE =  'SIGNALR_SEND_MESSAGE_FAILURE';